### ISSUE TITLE
Remove graphs that have 50% of more of data as "other" or "unknown"

### ISSUE THREAD

**Issue by GovInTrenches** [sc3/cook-convictions-data#16]
We should take these graphs out. They arn't really telling us anything.

**Comment by ghing** [comment]
Understood.  I also remember that we talked about this when we last met.  It's been a bit slower going because I've been trying to understand the reason for the high amounts of unknown.  In some cases, it's less a data black hole and more that the law/courts has a different focus than some of the questions that we're asking.  I'll try to push updated (or omitted) charts in the next couple of days.

**Comment by ghing** [comment]
These have been removed.  Closing.
